### ISSUE TITLE
2 race conditions in init phase leading to invisible USB related modal dialog boxes perceived as hangs

### ISSUE THREAD

**Issue by AntoineBlaisENAC** [espotek-org/Labrador#333]
Hello,

I am running the application on Debian GNU/Linux 12 (bookworm) after compilation from source.

Here is the content of the file labrador.log after running the command `./labrador 2>labrador.log`:

[labrador.log](https://github.com/user-attachments/files/20394968/labrador.log)
It seems to be a problem when using the libusb library.

Any help would be greatly appreciated,

Antoine

**Comment by EspoTek** [comment]
Does the same problem occur when you run the AppImage?

**Comment by AntoineBlaisENAC** [comment]
Yes unfortunately, exactly the same behavior with Labrador-82ea67c-x86_64.AppImage.
But maybe I have found a workaround: run the application, then plug the card. It seems to work normally, even if quitting with a core dump.

**Comment by chmielar** [comment]
I'm experiencing the same issue. Thank you for the tip, @AntoineBlaisENAC; it worked for me as well. I tested both the .deb and .AppImage versions, and I got the same result. I'm running Kubuntu 25.04, and the problem started after I recently upgraded from 24.10. Please let me know how I can help. I'm willing to run tests and provide any details you may need.

**Comment by EspoTek** [comment]
Thanks for sharing, guys.

So to confirm:
 - The issue occurs with both the source and the AppImage version
 - It only segfaults if the board is connected before the app is launched.
 - It only happens on newer versions of libusb (it was fine with whatever was included in *ubuntu 24.10, but not 25.04)

**Comment by turboencabulator** [comment]
I don't think the AppImage bundles libusb:
```
Skipping deployment of blacklisted library /lib/x86_64-linux-gnu/libusb-1.0.so.0
```

**Comment by EspoTek** [comment]
That'd do it.  Mind you, we should probably be using the system libusb anyway, right?

**Comment by chmielar** [comment]
@turboencabulator I'm not sure if it's relevant, but I also installed the application via .deb and encountered the same issue. Before upgrade to Kubuntu 25.04 it was good.

**Comment by turboencabulator** [comment]
In all three cases (building from source, AppImage, .deb) it should be using the system libusb.  Which version of libusb do you have?

**Comment by chmielar** [comment]
```
dpkg -l | grep libusb
ii  libgusb2:amd64                                           0.4.9-1                                    amd64        GLib wrapper around libusb1
ii  libhidapi-libusb0:amd64                                  0.14.0-1build1                             amd64        Multi-Platform library for communication with HID devices (libusb backend)
ii  libusb-0.1-4:amd64                                       2:0.1.12-35build1                          amd64        userspace USB programming library
ii  libusb-1.0-0:amd64                                       2:1.0.27-2                                 amd64        userspace USB programming library
ii  libusb-1.0-0-dev:amd64                                   2:1.0.27-2                                 amd64        userspace USB programming library development files
ii  libusb-1.0-doc                                           2:1.0.27-2                                 all          documentation for userspace USB programming
ii  libusb-dev                                               2:0.1.12-35build1                          amd64        userspace USB programming library development files
ii  libusbmuxd-2.0-7:amd64                                   2.1.0-1build1                              amd64        Client library to handle usbmux connections with iOS devices (library)
```

**Comment by turboencabulator** [comment]
> It seems to work normally, even if quitting with a core dump.

That core dump at the end has annoyed me for quite some time.  I've just pushed a fix for it.

Still trying to figure out the root cause of the original issue though.

**Comment by turboencabulator** [comment]
I've been using Ubuntu 24.04.2 which also has libusb 1.0.27 and it hasn't been a problem for me... until I deleted the config file (`~/.config/EspoTek/Labrador.conf`) and now I can reproduce it here as well.

Have you calibrated?  If not, does the problem go away once you do calibrate?

**Comment by AntoineBlaisENAC** [comment]
Hello,

Sorry for not responding, last days were quite busy. After proceeding to calibration the program now starts and runs without problem. Still have a core dump when quitting however.
A follow-up question: is it possible to use the Labrador with GNU Radio companion?

**Comment by turboencabulator** [comment]
I've tracked it down to a couple race conditions.

Race #&NoBreak;1:  The startup code instantiates a USB driver object, then does some other things, then reinitializes USB.  (I don't understand the purpose of the reinit yet, maybe @EspoTek can shed some light on it.)  The driver object will try to connect to the device after a short delay after it's been instantiated.  During normal startup, the reinit occurs before the first connection attempt.  But if calibration hasn't occurred, the "other things" previously mentioned include reading the config file and prompting the user if they'd like to calibrate once connected.  Basically in the time it takes to show the calibration dialog box and for the user to select yes/no, the driver will get a chance to connect.  Once connected, the reinit step has to do extra cleanup.

Race #&NoBreak;2:  There is a 100ms timeout before the libusb callback worker thread is manually killed, and that isn't enough time for all outstanding transfers to complete.  The destructor tries to free resources still in use, and it crashes.  This code needs a lot more attention, but for now I'm increasing the timeout.

**Comment by turboencabulator** [comment]
> A follow-up question: is it possible to use the Labrador with GNU Radio companion?

I've never used GNU Radio companion but it looks interesting.  I'd suggest creating a new discussion or feature request so it doesn't get lost in the noise on this ticket.

**Comment by AntoineBlaisENAC** [comment]
Done, I have started a new discussion on it.

**Comment by EspoTek** [comment]
> I've tracked it down to a couple race conditions.
> 
> Race #⁠1: The startup code instantiates a USB driver object, then does some other things, then reinitializes USB. (I don't understand the purpose of the reinit yet, maybe [@EspoTek](https://github.com/EspoTek) can shed some light on it.) The driver object will try to connect to the device after a short delay after it's been instantiated. During normal startup, the reinit occurs before the first connection attempt. But if calibration hasn't occurred, the "other things" previously mentioned include reading the config file and prompting the user if they'd like to calibrate once connected. Basically in the time it takes to show the calibration dialog box and for the user to select yes/no, the driver will get a chance to connect. Once connected, the reinit step has to do extra cleanup.
> 
> Race #⁠2: There is a 100ms timeout before the libusb callback worker thread is manually killed, and that isn't enough time for all outstanding transfers to complete. The destructor tries to free resources still in use, and it crashes. This code needs a lot more attention, but for now I'm increasing the timeout.

I'm not 100% sure why that reinit is there, or if it's still necessary, but I'm 90% sure it has something to do with getting the device to connect properly when the app is re-launched a second time.  Of course, I could be wrong there and it hasn't actually been necessary since some beta version from 2016.

**Comment by mi-hol** [comment]
> I've tracked it down to a couple race conditions.

@turboencabulator shall this issue be labeled as "bug" or can it be closed due to your workaround ?

**Comment by turboencabulator** [comment]
Yeah it's a bug, and the workaround doesn't completely avoid it.  It needs a more involved fix and I don't have a lot of time to devote to it at the moment.

**Comment by mi-hol** [comment]
**Updated**:

this bug or **a different USB-related bug** seems to be triggered **on Windows** mainly by a defective USB cable now

**Comment by freshLobster** [comment]
I don't know what the progress is on this bug, but I'd love to help out and contribute.

**Comment by freshLobster** [comment]
Ok I believe my patch in #407 fixes this bug. 
Built in Debian
run with: 

`labrador 2> labrador.log`

Here are my log files:

[labrador.log](https://github.com/user-attachments/files/25312250/labrador.log)

[labrador2.log](https://github.com/user-attachments/files/25312251/labrador2.log)

file [labrador.log](https://github.com/user-attachments/files/25312250/labrador.log) is the result of starting plugged in, unplugging, and plugging in again
file [labrador2.log](https://github.com/user-attachments/files/25312251/labrador2.log) is the result of starting unplugged, plugging in, and unplugging

please test my branch and PR in #407

**Comment by mi-hol** [comment]
@AntoineBlaisENAC @chmielar in case you could spare some time to test the proposed fix in #407 we'd greatly appreciate your contribution :)

**Comment by AntoineBlaisENAC** [comment]
Hi, I have just cloned the repository on my two laptops (Debian GNU/Linux 12 (bookworm) and Debian GNU/Linux 13 (trixie)), it works like a charm on both without even applying the fix! May be some package update?

**Comment by mi-hol** [comment]
> I have just cloned the repository

to be exact, does this translate to commit 58f6d52452c3b9caf45b099c701f5b4f4e1b8fe2 ?

**Comment by AntoineBlaisENAC** [comment]
Below are the first lines returned by the git log command:
commit 701cf55c8c2cf196454668cab0386716f8814ec6
Author: mi-hol <22799428+mi-hol@users.noreply.github.com>
Date:   Wed Feb 11 14:03:47 2026 +0100

    Add Dependabot configuration for GitHub Actions

**Comment by mi-hol** [comment]
> It seems to be a problem when using the libusb library.

> (Debian GNU/Linux 12 (bookworm) and Debian GNU/Linux 13 (trixie)), it works like a charm on both without even applying the fix!

@AntoineBlaisENAC above comment is just related to your inital comment"Still have a core dump when quitting".

Is this correct understand or did I missing anything?

Assuming above is correct, likely @turboencabulator's workaround in https://github.com/espotek-org/Labrador/issues/333#issuecomment-2927751242 has already resolved the majority of crashes on Linux.

@AntoineBlaisENAC you could help us a lot by repeating your testing with commit e12751ce3ceb93cba7df16f9adf957189f07c38b and reporting result.

in case this commit crashes, only later fixes by @brentfpage resolved the bug

**Comment by AntoineBlaisENAC** [comment]
Is it correct if I do git reset --hard e12751c then ./labrador_bootstrap_pi then run labrador after compilation ended?
If yes, no more core dump when quitting on both PCs.

**Comment by freshLobster** [comment]
My fix was built from [my fork](https://github.com/freshLobster/Labrador) of labrador. 
The build commands were from the wiki as follows:

```
sudo apt-get update
sudo apt-get install build-essential 
sudo apt-get install pkg-config
sudo apt-get install git
sudo apt-get install qtbase5-dev
sudo apt-get install qtchooser
sudo apt-get install qt5-qmake
sudo apt-get install qtbase5-dev-tools
sudo apt-get install libusb-1.0-0-dev 
sudo apt-get install libfftw3-dev
sudo apt-get install libeigen3-dev
cd ~
git clone https://github.com/freshLobster/Labrador
cd ~/Labrador/Desktop_Interface
QT_SELECT=qt5 qmake
make
sudo make install
sudo ldconfig
labrador 2> labrador.log
```
I repeatedly plugged and unplugged the usb cable without the device calibrated and also after calibration. I tried disconnecting it and reconnecting it suddenly to simulate a faulty usb cable. My main goal was baking in the race preventing measures such that functionality isn't dependent on libusb versions.
Without the fix it assumes the connection is terminated and jumps back to reinit without any actual positive confirmation that all transfers were terminated and it's safe to attempt a reinit. The default behavior shouldn't rely on a magic number 
time interval with no check. That's just my opinion for clean reliable software.
> **Updated**:
> 
> this bug or **a different USB-related bug** seems to be triggered **on Windows** mainly by a defective USB cable now

@mi-hol If I have the time I can apply the same fix for Windows so a defective cable wont crash the program.

**Comment by EspoTek** [comment]
I've merged @freshLobster's fix for Linux.  A similar fix for Windows would be greatly appreciated if you can spare the time!

**Comment by mi-hol** [comment]
@freshLobster I'll keep this issue open but with labeling changed to "OS:Windows"
Hope to hear from you soon :)

**Comment by mi-hol** [comment]
> The default behavior shouldn't rely on a magic number time interval with no check. That's just my opinion for clean reliable software.

makes perfect sense! Well spotted!
